server:
  port: 8100
eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka
resilience4j:
  ratelimiter:    instances:      default: 
        limit-for-period: 2
        limit-refresh-period: 10s #em 10 segundos posso fazer duas requisicoes  retry:    instances:      default:
        max-attempts: 5
      foo-bar:
        max-attempts: 4
        wait-duration: 4s
spring:  application:    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306
    schemas: book_service
    user: root
    password: 1234
  jackson:
    default-property-inclusion: non-null    serialization:      fail-on-empty-beans: false